# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    # Send a single PR per run, instead of one per dependency to make testing and verification easier.
    groups:
      production-dependencies:
        dependency-type: "production"
        applies-to: "security-updates"
