from __future__ import annotations

class Output:
    stderr: bytes
    stdout: bytes
    exit_code: int | str

    def __init__(self, stdout: bytes, stderr: bytes, exit_code: int | str) -> None: ...

class TestCase:
    def __init__(
        self,
        title: str,
        shell_expression: str,
        exit_code: int,
        expectations: list[str],
        line_number: int | None,
        cram_compat: bool = False,
    ) -> None: ...
    @property
    def title(self) -> str: ...
    @property
    def shell_expression(self) -> str: ...
    @property
    def exit_code(self) -> int: ...
    @property
    def expectations(self) -> list[tuple[str, str, bool, bool]]: ...
    @property
    def line_number(self) -> int: ...
    def validate(
        self, output: Output, location: str | None = None
    ) -> tuple[bool, str]: ...

class CramParser:
    def __init__(self) -> None: ...
    def parse(self, text: str) -> list[TestCase]: ...

class MarkdownParser:
    def __init__(self, languages: list[str]) -> None: ...
    @staticmethod
    def default() -> MarkdownParser: ...
    def parse(self, text: str) -> list[TestCase]: ...

def hello_world() -> str: ...
