name: Cargo Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  cargo:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_REGISTRY_TOKEN }}
